openapi: 3.0.1
info:
  contact:
    email: otae@fundaciobit.org
    name: Departament de Govern Digital a la Fundació Bit
    url: http://governdigital.fundaciobit.org
  description: Conjunt de Serveis REST de PortaFIB per atendre consultes generiques
    de Portafib
  license:
    name: European Union Public Licence (EUPL v1.2)
    url: https://joinup.ec.europa.eu/sites/default/files/custom-page/attachment/eupl_v1.2_es.pdf
  title: API Interna de PortaFIB de consulta de serveis d'utilitat
  version: 1.0-SNAPSHOT
externalDocs:
  description: Java API Interna Client (Github Source Code)
  url: https://github.com/GovernIB/portafib/tree/portafib-2.2/
servers:
- url: /portafibapi/interna
- url: http://localhost:8080/portafibapi/interna
- url: https://dev.caib.es/portafibapi/interna
- url: https://proves.caib.es/portafibapi/interna
- url: https://se.caib.es/portafibapi/interna
- url: https://www.caib.es/portafibapi/interna
tags:
- description: Firma en servidor
  name: Firma en Servidor v1
- description: Utilitats
  name: Utils v1
paths:
  /secure/firmaenservidor/v1/signdocument:
    post:
      operationId: signdocument
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FirmaSimpleSignDocumentRequest'
        description: Operacio de firma simple en servidor d'un document
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FirmaSimpleSignatureRest'
          description: Operació realitzada correctament
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestExceptionInfo'
          description: Paràmetres incorrectes
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestExceptionInfo'
          description: Error no controlat
      security:
      - BasicAuth: []
      summary: Operacio de firma simple en servidor d'un document
      tags:
      - Firma en Servidor v1
      x-content-type: application/json
      x-accepts: application/json
  /secure/firmaenservidor/v1/versio:
    get:
      operationId: versio
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
          description: Retornada correctament la versió d'aquest Servei
        "401":
          content:
            application/json:
              schema:
                type: string
          description: No Autenticat
        "403":
          content:
            application/json:
              schema:
                type: string
          description: No Autoritzat
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestExceptionInfo'
          description: Error no controlat
        "510":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConstantsWs'
          description: Només s'utilitza per crear fitxer de constants...
      security:
      - BasicAuth: []
      summary: Retorna la versió d'aquest Servei
      tags:
      - Firma en Servidor v1
      x-accepts: application/json
  /secure/utils/v1/getAvailableLanguages:
    get:
      operationId: getAvailableLanguages
      parameters:
      - description: Idioma en que s'han de retornar les dades(Només suportat 'ca'
          o 'es')
        examples:
          Català:
            description: Català
            value: ca
          Castellano:
            description: Castellano
            value: es
        explode: true
        in: query
        name: language
        required: false
        schema:
          default: ca
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AvailableLanguagesRest'
          description: Operació realitzada correctament
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestExceptionInfo'
          description: Paràmetres incorrectes
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestExceptionInfo'
          description: Error no controlat
      security:
      - BasicAuth: []
      summary: Retorna els idiomes disponibles.
      tags:
      - Utils v1
      x-accepts: application/json
  /secure/utils/v1/getAvailableProfiles:
    get:
      operationId: getAvailableProfiles
      parameters:
      - description: Idioma en que s'han de retornar les dades(Només suportat 'ca'
          o 'es')
        examples:
          Català:
            description: Català
            value: ca
          Castellano:
            description: Castellano
            value: es
        explode: true
        in: query
        name: language
        required: false
        schema:
          default: ca
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AvailableProfilesRest'
          description: Operació realitzada correctament
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestExceptionInfo'
          description: Paràmetres incorrectes
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestExceptionInfo'
          description: Error no controlat
      security:
      - BasicAuth: []
      summary: Retorna els perfils de firma.
      tags:
      - Utils v1
      x-accepts: application/json
  /secure/utils/v1/tipusdocumentalslist:
    get:
      operationId: tipusdocumentalslist
      parameters:
      - description: Idioma en que s'han de retornar les dades(Només suportat 'ca'
          o 'es')
        examples:
          Català:
            description: Català
            value: ca
          Castellano:
            description: Castellano
            value: es
        explode: true
        in: query
        name: language
        required: false
        schema:
          default: ca
          type: string
        style: form
      - description: Filtre pel nom de l'usuari aplicacio. Opcional.
        explode: true
        in: query
        name: appuser
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LlistaTipusDocumentalRest'
          description: Operació realitzada correctament
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestExceptionInfo'
          description: Paràmetres incorrectes
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestExceptionInfo'
          description: Error no controlat
      security:
      - BasicAuth: []
      summary: Retorna la llista de tipus documentals disponibles.
      tags:
      - Utils v1
      x-accepts: application/json
components:
  schemas:
    FirmaSimpleCommonInfo:
      example:
        signProfile: signProfile
        administrationID: administrationID
        organizationID: organizationID
        signerEmail: signerEmail
        languageUI: languageUI
        username: username
      properties:
        signProfile:
          type: string
        languageUI:
          type: string
        username:
          type: string
        administrationID:
          type: string
        organizationID:
          type: string
        signerEmail:
          type: string
      type: object
    FirmaSimpleFile:
      example:
        data: data
        mime: mime
        nom: nom
      properties:
        nom:
          type: string
        mime:
          type: string
        data:
          description: Contingut del fitxer. En llistats aquest camp vendrà buit.
          format: byte
          type: string
      type: object
    FirmaSimpleFileInfoSignature:
      example:
        reason: reason
        additionalInformation:
        - value: value
          key: key
        - value: value
          key: key
        expedientNom: expedientNom
        languageSign: languageSign
        documentType: 6
        signID: signID
        expedientCodi: expedientCodi
        procedimentCodi: procedimentCodi
        procedimentNom: procedimentNom
        signNumber: 0
        fileToSign:
          data: data
          mime: mime
          nom: nom
        name: name
        location: location
        previusSignatureDetachedFile:
          data: data
          mime: mime
          nom: nom
        expedientUrl: expedientUrl
      properties:
        fileToSign:
          $ref: '#/components/schemas/FirmaSimpleFile'
        previusSignatureDetachedFile:
          $ref: '#/components/schemas/FirmaSimpleFile'
        signID:
          type: string
        name:
          type: string
        reason:
          type: string
        location:
          type: string
        signNumber:
          format: int32
          type: integer
        languageSign:
          type: string
        expedientCodi:
          type: string
        expedientNom:
          type: string
        expedientUrl:
          type: string
        procedimentCodi:
          type: string
        procedimentNom:
          type: string
        documentType:
          format: int64
          type: integer
        additionalInformation:
          items:
            $ref: '#/components/schemas/FirmaSimpleKeyValue'
          type: array
      type: object
    FirmaSimpleKeyValue:
      example:
        value: value
        key: key
      properties:
        key:
          type: string
        value:
          type: string
      type: object
    FirmaSimpleSignDocumentRequest:
      example:
        fileInfoSignature:
          reason: reason
          additionalInformation:
          - value: value
            key: key
          - value: value
            key: key
          expedientNom: expedientNom
          languageSign: languageSign
          documentType: 6
          signID: signID
          expedientCodi: expedientCodi
          procedimentCodi: procedimentCodi
          procedimentNom: procedimentNom
          signNumber: 0
          fileToSign:
            data: data
            mime: mime
            nom: nom
          name: name
          location: location
          previusSignatureDetachedFile:
            data: data
            mime: mime
            nom: nom
          expedientUrl: expedientUrl
        commonInfo:
          signProfile: signProfile
          administrationID: administrationID
          organizationID: organizationID
          signerEmail: signerEmail
          languageUI: languageUI
          username: username
      properties:
        commonInfo:
          $ref: '#/components/schemas/FirmaSimpleCommonInfo'
        fileInfoSignature:
          $ref: '#/components/schemas/FirmaSimpleFileInfoSignature'
      type: object
    FirmaSimpleCustodyInfo:
      example:
        validationFileUrl: validationFileUrl
        originalFileDirectURL: originalFileDirectURL
        expedientID: expedientID
        custodyID: custodyID
        csv: csv
        eniFileDirectUrl: eniFileDirectUrl
        csvValidationWeb: csvValidationWeb
        documentID: documentID
        csvGenerationDefinition: csvGenerationDefinition
        printableFileDirectUrl: printableFileDirectUrl
      properties:
        custodyID:
          type: string
        csv:
          type: string
        csvValidationWeb:
          type: string
        validationFileUrl:
          type: string
        csvGenerationDefinition:
          type: string
        originalFileDirectURL:
          type: string
        printableFileDirectUrl:
          type: string
        eniFileDirectUrl:
          type: string
        expedientID:
          type: string
        documentID:
          type: string
      type: object
    FirmaSimpleSignatureRest:
      example:
        signedFileInfo:
          signerInfo:
            issuerCert: issuerCert
            eniRolFirma: eniRolFirma
            additionalInformation:
            - value: value
              key: key
            - value: value
              key: key
            subjectCert: subjectCert
            eniSignerName: eniSignerName
            eniSignLevel: eniSignLevel
            signDate: 2000-01-23T04:56:07.000+00:00
            eniSignerAdministrationId: eniSignerAdministrationId
            serialNumberCert: serialNumberCert
          signaturesTableLocation: 5
          signOperation: 6
          custodyInfo:
            validationFileUrl: validationFileUrl
            originalFileDirectURL: originalFileDirectURL
            expedientID: expedientID
            custodyID: custodyID
            csv: csv
            eniFileDirectUrl: eniFileDirectUrl
            csvValidationWeb: csvValidationWeb
            documentID: documentID
            csvGenerationDefinition: csvGenerationDefinition
            printableFileDirectUrl: printableFileDirectUrl
          eniTipoFirma: eniTipoFirma
          eniPerfilFirma: eniPerfilFirma
          validationInfo:
            checkDocumentModifications: true
            noCheckValidationReason: noCheckValidationReason
            checkValidationSignature: true
            checkAdministrationIDOfSigner: true
          signType: signType
          signMode: 1
          signAlgorithm: signAlgorithm
          timeStampIncluded: true
          policyIncluded: true
        signedFile:
          data: data
          mime: mime
          nom: nom
        signID: signID
        status:
          errorStackTrace: errorStackTrace
          errorMessage: errorMessage
          status: 0
      properties:
        signID:
          type: string
        status:
          $ref: '#/components/schemas/FirmaSimpleStatus'
        signedFile:
          $ref: '#/components/schemas/FirmaSimpleFile'
        signedFileInfo:
          $ref: '#/components/schemas/FirmaSimpleSignedFileInfo'
      type: object
    FirmaSimpleSignedFileInfo:
      example:
        signerInfo:
          issuerCert: issuerCert
          eniRolFirma: eniRolFirma
          additionalInformation:
          - value: value
            key: key
          - value: value
            key: key
          subjectCert: subjectCert
          eniSignerName: eniSignerName
          eniSignLevel: eniSignLevel
          signDate: 2000-01-23T04:56:07.000+00:00
          eniSignerAdministrationId: eniSignerAdministrationId
          serialNumberCert: serialNumberCert
        signaturesTableLocation: 5
        signOperation: 6
        custodyInfo:
          validationFileUrl: validationFileUrl
          originalFileDirectURL: originalFileDirectURL
          expedientID: expedientID
          custodyID: custodyID
          csv: csv
          eniFileDirectUrl: eniFileDirectUrl
          csvValidationWeb: csvValidationWeb
          documentID: documentID
          csvGenerationDefinition: csvGenerationDefinition
          printableFileDirectUrl: printableFileDirectUrl
        eniTipoFirma: eniTipoFirma
        eniPerfilFirma: eniPerfilFirma
        validationInfo:
          checkDocumentModifications: true
          noCheckValidationReason: noCheckValidationReason
          checkValidationSignature: true
          checkAdministrationIDOfSigner: true
        signType: signType
        signMode: 1
        signAlgorithm: signAlgorithm
        timeStampIncluded: true
        policyIncluded: true
      properties:
        signOperation:
          format: int32
          type: integer
        signType:
          type: string
        signAlgorithm:
          type: string
        signMode:
          format: int32
          type: integer
        signaturesTableLocation:
          format: int32
          type: integer
        timeStampIncluded:
          type: boolean
        policyIncluded:
          type: boolean
        eniTipoFirma:
          type: string
        eniPerfilFirma:
          type: string
        signerInfo:
          $ref: '#/components/schemas/FirmaSimpleSignerInfo'
        custodyInfo:
          $ref: '#/components/schemas/FirmaSimpleCustodyInfo'
        validationInfo:
          $ref: '#/components/schemas/FirmaSimpleValidationInfo'
      type: object
    FirmaSimpleSignerInfo:
      example:
        issuerCert: issuerCert
        eniRolFirma: eniRolFirma
        additionalInformation:
        - value: value
          key: key
        - value: value
          key: key
        subjectCert: subjectCert
        eniSignerName: eniSignerName
        eniSignLevel: eniSignLevel
        signDate: 2000-01-23T04:56:07.000+00:00
        eniSignerAdministrationId: eniSignerAdministrationId
        serialNumberCert: serialNumberCert
      properties:
        eniRolFirma:
          type: string
        eniSignerName:
          type: string
        eniSignerAdministrationId:
          type: string
        eniSignLevel:
          type: string
        signDate:
          format: date-time
          type: string
        serialNumberCert:
          type: string
        issuerCert:
          type: string
        subjectCert:
          type: string
        additionalInformation:
          items:
            $ref: '#/components/schemas/FirmaSimpleKeyValue'
          type: array
      type: object
    FirmaSimpleStatus:
      example:
        errorStackTrace: errorStackTrace
        errorMessage: errorMessage
        status: 0
      properties:
        status:
          format: int32
          type: integer
        errorMessage:
          type: string
        errorStackTrace:
          type: string
      type: object
    FirmaSimpleValidationInfo:
      example:
        checkDocumentModifications: true
        noCheckValidationReason: noCheckValidationReason
        checkValidationSignature: true
        checkAdministrationIDOfSigner: true
      properties:
        checkAdministrationIDOfSigner:
          type: boolean
        checkDocumentModifications:
          type: boolean
        checkValidationSignature:
          type: boolean
        noCheckValidationReason:
          type: string
      type: object
    RestExceptionInfo:
      description: Estructura de dades utilitzada per passar informació d'un error
      example:
        code: 5
        causeStackTrace: causeStackTrace
        causeException: causeException
        errorMessage: errorMessage
        stackTrace: stackTrace
      properties:
        code:
          description: Codi de HTTP de l'error. Veure https://en.wikipedia.org/wiki/List_of_HTTP_status_codes.
          format: int32
          type: integer
        errorMessage:
          description: Missatge de l'error
          type: string
        stackTrace:
          description: Stacktrace de l'excepció si n'hi hagués.
          type: string
        causeException:
          description: Tipus de l'excepció origen (cause) si n'hi hagués.
          type: string
        causeStackTrace:
          description: Stacktrace de l'excepció origen (cause) si n'hi hagués.
          type: string
      required:
      - code
      - errorMessage
      type: object
    ConstantsWs:
      example:
        STATUS_FINAL_OK: 1
        STATUS_FINAL_ERROR: 5
        STATUS_INITIALIZING: 0
        STATUS_IN_PROGRESS: 6
        STATUS_CANCELLED: 5
      properties:
        STATUS_INITIALIZING:
          default: 0
          description: Codi d'estat d'una petició de firma que indica un que s'esta
            inicialitzant
          format: int32
          readOnly: true
          type: integer
        STATUS_IN_PROGRESS:
          default: 1
          description: Codi d'estat d'una petició de firma que indica un que esta
            en procés
          format: int32
          readOnly: true
          type: integer
        STATUS_FINAL_OK:
          default: 2
          description: Codi d'estat d'una petició de firma que indica que ha finalitzat
            correctament
          format: int32
          readOnly: true
          type: integer
        STATUS_FINAL_ERROR:
          default: -1
          description: Codi d'estat d'una petició de firma que indica que ha finalitzat
            amb errors
          format: int32
          readOnly: true
          type: integer
        STATUS_CANCELLED:
          default: -2
          description: Codi d'estat d'una petició de firma que indica que ha sigut
            cancelada
          format: int32
          readOnly: true
          type: integer
      required:
      - STATUS_CANCELLED
      - STATUS_FINAL_ERROR
      - STATUS_FINAL_OK
      - STATUS_INITIALIZING
      - STATUS_IN_PROGRESS
      type: object
    ApisIBKeyValue:
      example:
        value: value
        key: key
      properties:
        key:
          type: string
        value:
          type: string
      type: object
    AvailableLanguagesRest:
      example:
        list:
        - value: value
          key: key
        - value: value
          key: key
      properties:
        list:
          items:
            $ref: '#/components/schemas/ApisIBKeyValue'
          type: array
      type: object
    AvailableProfile:
      example:
        code: code
        name: name
        description: description
      properties:
        code:
          type: string
        name:
          type: string
        description:
          type: string
      type: object
    AvailableProfilesRest:
      example:
        data:
        - code: code
          name: name
          description: description
        - code: code
          name: name
          description: description
        language: language
      properties:
        data:
          items:
            $ref: '#/components/schemas/AvailableProfile'
          type: array
        language:
          type: string
      type: object
    LlistaTipusDocumentalRest:
      example:
        data:
        - tipusDocumentNTI: 6
          tipusDocumentID: 0
          nom: nom
        - tipusDocumentNTI: 6
          tipusDocumentID: 0
          nom: nom
        language: language
      properties:
        data:
          items:
            $ref: '#/components/schemas/TipusDocumentalRest'
          type: array
        language:
          type: string
      type: object
    TipusDocumentalRest:
      example:
        tipusDocumentNTI: 6
        tipusDocumentID: 0
        nom: nom
      properties:
        tipusDocumentID:
          format: int64
          type: integer
        nom:
          type: string
        tipusDocumentNTI:
          format: int64
          type: integer
      type: object
  securitySchemes:
    BasicAuth:
      scheme: basic
      type: http

