openapi: 3.0.1
info:
  contact:
    email: otae@fundaciobit.org
    name: Departament de Govern Digital a la Fundació Bit
    url: http://governdigital.fundaciobit.org
  description: Conjunt de Serveis REST de PortaFIB per atendre consultes generiques
    de Portafib
  license:
    name: European Union Public Licence (EUPL v1.2)
    url: https://joinup.ec.europa.eu/sites/default/files/custom-page/attachment/eupl_v1.2_es.pdf
  title: API Interna de PortaFIB de consulta de serveis d'utilitat
  version: 1.0-SNAPSHOT
externalDocs:
  description: Java API Interna Client (Github Source Code)
  url: https://github.com/GovernIB/portafib/tree/portafib-2.2/
servers:
- url: /portafibapi/interna
- url: http://localhost:8080/portafibapi/interna
- url: https://dev.caib.es/portafibapi/interna
- url: https://proves.caib.es/portafibapi/interna
- url: https://se.caib.es/portafibapi/interna
- url: https://www.caib.es/portafibapi/interna
tags:
- description: Utilitats
  name: Utils v1
paths:
  /secure/utils/v1/getAvailableLanguages:
    get:
      operationId: getAvailableLanguages
      parameters:
      - description: Idioma en que s'han de retornar les dades(Només suportat 'ca'
          o 'es')
        examples:
          Català:
            description: Català
            value: ca
          Castellano:
            description: Castellano
            value: es
        explode: true
        in: query
        name: language
        required: false
        schema:
          default: ca
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AvailableLanguagesRest'
          description: Operació realitzada correctament
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestExceptionInfo'
          description: Paràmetres incorrectes
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestExceptionInfo'
          description: Error no controlat
      security:
      - BasicAuth: []
      summary: Retorna els idiomes disponibles.
      tags:
      - Utils v1
      x-accepts: application/json
  /secure/utils/v1/getAvailableProfiles:
    get:
      operationId: getAvailableProfiles
      parameters:
      - description: Idioma en que s'han de retornar les dades(Només suportat 'ca'
          o 'es')
        examples:
          Català:
            description: Català
            value: ca
          Castellano:
            description: Castellano
            value: es
        explode: true
        in: query
        name: language
        required: false
        schema:
          default: ca
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AvailableProfilesRest'
          description: Operació realitzada correctament
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestExceptionInfo'
          description: Paràmetres incorrectes
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestExceptionInfo'
          description: Error no controlat
      security:
      - BasicAuth: []
      summary: Retorna els perfils de firma.
      tags:
      - Utils v1
      x-accepts: application/json
  /secure/utils/v1/tipusdocumentalslist:
    get:
      operationId: tipusdocumentalslist
      parameters:
      - description: Idioma en que s'han de retornar les dades(Només suportat 'ca'
          o 'es')
        examples:
          Català:
            description: Català
            value: ca
          Castellano:
            description: Castellano
            value: es
        explode: true
        in: query
        name: language
        required: false
        schema:
          default: ca
          type: string
        style: form
      - description: Filtre pel nom de l'usuari aplicacio. Opcional.
        explode: true
        in: query
        name: appuser
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LlistaTipusDocumentalRest'
          description: Operació realitzada correctament
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestExceptionInfo'
          description: Paràmetres incorrectes
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestExceptionInfo'
          description: Error no controlat
      security:
      - BasicAuth: []
      summary: Retorna la llista de tipus documentals disponibles.
      tags:
      - Utils v1
      x-accepts: application/json
components:
  schemas:
    AvailableLanguagesRest:
      example:
        list:
        - value: value
          key: key
        - value: value
          key: key
      properties:
        list:
          items:
            $ref: '#/components/schemas/CommonsRestKeyValue'
          type: array
      type: object
    CommonsRestKeyValue:
      example:
        value: value
        key: key
      properties:
        key:
          type: string
        value:
          type: string
      type: object
    RestExceptionInfo:
      description: Estructura de dades utilitzada per passar informació d'un error
      example:
        code: 0
        causeStackTrace: causeStackTrace
        causeException: causeException
        errorMessage: errorMessage
        stackTrace: stackTrace
      properties:
        code:
          description: Codi de HTTP de l'error. Veure https://en.wikipedia.org/wiki/List_of_HTTP_status_codes.
          format: int32
          type: integer
        errorMessage:
          description: Missatge de l'error
          type: string
        stackTrace:
          description: Stacktrace de l'excepció si n'hi hagués.
          type: string
        causeException:
          description: Tipus de l'excepció origen (cause) si n'hi hagués.
          type: string
        causeStackTrace:
          description: Stacktrace de l'excepció origen (cause) si n'hi hagués.
          type: string
      required:
      - code
      - errorMessage
      type: object
    AvailableProfile:
      example:
        code: code
        name: name
        description: description
      properties:
        code:
          type: string
        name:
          type: string
        description:
          type: string
      type: object
    AvailableProfilesRest:
      example:
        data:
        - code: code
          name: name
          description: description
        - code: code
          name: name
          description: description
        language: language
      properties:
        data:
          items:
            $ref: '#/components/schemas/AvailableProfile'
          type: array
        language:
          type: string
      type: object
    LlistaTipusDocumentalRest:
      example:
        data:
        - tipusDocumentNTI: 6
          tipusDocumentID: 0
          nom: nom
        - tipusDocumentNTI: 6
          tipusDocumentID: 0
          nom: nom
        language: language
      properties:
        data:
          items:
            $ref: '#/components/schemas/TipusDocumentalRest'
          type: array
        language:
          type: string
      type: object
    TipusDocumentalRest:
      example:
        tipusDocumentNTI: 6
        tipusDocumentID: 0
        nom: nom
      properties:
        tipusDocumentID:
          format: int64
          type: integer
        nom:
          type: string
        tipusDocumentNTI:
          format: int64
          type: integer
      type: object
  securitySchemes:
    BasicAuth:
      scheme: basic
      type: http

